[package]
name = "po-async-web-framework"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2.1"
env_logger = "0.10"
serde = { version = "1.0.214", features = ["derive"] }
dotenv = "0.15"
tokio = { version = "1.39.3", features = ["full"] }
