[package]
name = "po-async-web-framework"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2.1"
env_logger = "0.10"
dotenv = "0.15"
serde = { version = "1.0.214", features = ["derive"] }
tts_rust = "0.3.5"
actix-rt = "2.10.0"
serde_json = "1.0"
